AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Simple static website using S3 and API gateway
Parameters:
  stackName:
    Description: The stack or project name
    Type: String
    MinLength: 1
    MaxLength: 50
  bucketName:
    Description: The S3 bucket name (lowercase letters, numbers, dots, dashes)
    Type: String
    MinLength: 1
    MaxLength: 50
  stageName:
    Description: The REST API stage (version) name
    Type: String
    MinLength: 1
    MaxLength: 50
    Default: v1

Resources:

  websiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketName

  bucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref bucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref bucketName
                - /*
            Principal:
              Service: "apigateway.amazonaws.com"
            Sid: "APIProxyBucketPolicy"
            Condition:
              ArnLike:
                "aws:SourceArn": !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway.RestApiId}/*/GET/"

  getBucketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: bucketRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:GetObject"
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref bucketName
                    - /*

  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BinaryMediaTypes:
        - "*/*"
      DisableExecuteApiEndpoint: false
      EndpointConfiguration:
        Types:
          - "EDGE"
      FailOnWarnings: true
      Name: !Join
        - '-'
        - - !Ref stackName
          - "api-gateway"
      Policy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "execute-api:Invoke"
            Resource: "execute-api:/*"

  apiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - apiStaticGET
      - apiRootGET
      - apiStaticRootGET
      - apiMethod
    Properties:
      RestApiId: !GetAtt apiGateway.RestApiId
      StageName: !Ref stageName

  apiRootGET:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      MethodResponses:
        - StatusCode: '200'
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Content-Length: true
            method.response.header.Content-Encoding: false
      Integration:
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS
        Credentials: !GetAtt getBucketRole.Arn
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${bucketName}/index.html"
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Content-Length: integration.response.header.Content-Length
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Content-Encoding: integration.response.header.Content-Encoding
      ResourceId: !GetAtt apiGateway.RootResourceId
      RestApiId: !GetAtt apiGateway.RestApiId

  apiStaticPath:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt apiGateway.RootResourceId
      PathPart: 'static'
      RestApiId: !GetAtt apiGateway.RestApiId

  apiStaticResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref apiStaticPath
      PathPart: '{object}'
      RestApiId: !GetAtt apiGateway.RestApiId

  apiStaticGET:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      RequestParameters:
        method.request.path.object: true
      MethodResponses:
        - StatusCode: '200'
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Content-Length: true
            method.response.header.Content-Encoding: false
      Integration:
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS
        Credentials: !GetAtt getBucketRole.Arn
        RequestParameters:
          integration.request.path.object: method.request.path.object
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${bucketName}/{object}"
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Content-Length: integration.response.header.Content-Length
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Content-Encoding: integration.response.header.Content-Encoding
      ResourceId: !Ref apiStaticResource
      RestApiId: !GetAtt apiGateway.RestApiId

  apiStaticRootGET:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      MethodResponses:
        - StatusCode: '200'
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Content-Length: true
            method.response.header.Content-Encoding: false
      Integration:
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS
        Credentials: !GetAtt getBucketRole.Arn
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${bucketName}/index.html"
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Content-Length: integration.response.header.Content-Length
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Content-Encoding: integration.response.header.Content-Encoding
      ResourceId: !Ref apiStaticPath
      RestApiId: !GetAtt apiGateway.RestApiId

  apiRootPath:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt apiGateway.RootResourceId
      PathPart: 'api'
      RestApiId: !GetAtt apiGateway.RestApiId

  apiPath:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref apiRootPath
      PathPart: '{path+}'
      RestApiId: !GetAtt apiGateway.RestApiId

  apiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      MethodResponses:
        - StatusCode: '200'
      Integration:
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${theLambda.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: '200'
      ResourceId: !Ref apiPath
      RestApiId: !GetAtt apiGateway.RestApiId

  theLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - '-'
        - - !Ref stackName
          - "lambda"
      Handler: index.handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 128
      LoggingConfig:
        LogFormat: Text
        LogGroup: !Ref lambdaLogGroup
      InlineCode: |
          import json
          def handler(event, _):
              print(event)
              return {
          "statusCode": 200,
          "headers": {"X-test": "Test"},
          "body": json.dumps({ "message" : "Hello."}),
          }

  lambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupClass: STANDARD
      RetentionInDays: 3
      LogGroupName: !Join
        - '-'
        - - !Ref stackName
          - "lambda-log"

  theLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - apiGateway
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref theLambda
      Principal: apigateway.amazonaws.com
